messages = {
    "en": {
        "ADMIN_CREATED_SUCCESSFULLY": "ADMIN_CREATED_SUCCESSFULLY",
        "PROFILE_PIC_IS_REQUIRED": "PROFILE_PIC_IS_REQUIRED",
        "VALIDATION_COMPLETED": "VALIDATION_COMPLETED"
    },
    "ar": {
        "ADMIN_CREATED_SUCCESSFULLY": "ADMIN_CREATED_SUCCESSFULLY",
        "PROFILE_PIC_IS_REQUIRED": "PROFILE_PIC_IS_REQUIRED",
        "VALIDATION_COMPLETED": "VALIDATION_COMPLETED"
    }
}